"use client";

import React, { useContext, useEffect, useMemo, useRef } from "react";
import "../styles/globals.css";
import Header from "../components/Header";
import AsideMenu from "@/components/AsideMenu";
import HeaderWrapper from "@/components/HeaderWrapper";
import Footer from "@/components/Footer";
import Head from "next/head";
import CartProvider from "@/contexts/CartContextProvider";
import ScrollProvider, {
	ScrollContext,
} from "@/contexts/ScrollContextProvider";
import CookiesConsent, { CookiesModalRef } from "@/components/CookiesConsent";
import Cookies from "js-cookie";
import { cookiePermissionKey } from "@/utils/constants";

export default function LayoutContent({
	children,
}: {
	children: React.ReactNode;
}) {
	const { scrollEnabled } = useContext(ScrollContext);

	const cookiesModalRef = useRef<CookiesModalRef>();

	const overflowY = useMemo(
		() => (scrollEnabled ? "auto" : "hidden"),
		[scrollEnabled]
	);

	const checkCookiesPermission = () => {
		const status = Cookies.get(cookiePermissionKey);
		if (status) return;
		cookiesModalRef.current?.open();
	};

	useEffect(() => {
		checkCookiesPermission();
	}, []);

	return (
		<html style={{ overflowY }} lang="en">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<body>
				<HeaderWrapper />
				{children}
				<Footer />
				<CookiesConsent ref={cookiesModalRef} />
			</body>
		</html>
	);
}
