"use client";

import React, { useContext, useEffect, useMemo, useRef, useState } from "react";
import "../styles/globals.css";
import Header from "../components/Header";
import AsideMenu, { AsideMenuRef } from "@/components/AsideMenu";
import HeaderWrapper from "@/components/HeaderWrapper";
import Footer from "@/components/Footer";
import Head from "next/head";
import CartProvider from "@/contexts/CartContextProvider";
import ScrollProvider, {
	ScrollContext,
} from "@/contexts/ScrollContextProvider";
import CookiesConsent, { CookiesModalRef } from "@/components/CookiesConsent";
import Cookies from "js-cookie";
import { cookiePermissionKey } from "@/utils/constants";
import NotificationsContextProvider from "@/contexts/NotificationsContextProvider";
import SearchWindow, { SearchWindowRef } from "@/components/SearchWindow";
import CartModal, { CartModalRef } from "@/components/CartModal";
import { ProductCategory } from "@/models/product";
import { MenuItem } from "@/models/asideMenuItem";
import { getFirestoreDatabase } from "@/services/firebase/firebase";
import { collection, getDocs } from "firebase/firestore";

export default function LayoutContent({
	children,
}: {
	children: React.ReactNode;
}) {
	const { scrollEnabled } = useContext(ScrollContext);

	const overflowY = useMemo(
		() => (scrollEnabled ? "auto" : "hidden"),
		[scrollEnabled]
	);

	return (
		<html style={{ overflowY }} lang="en">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<body>
				<NotificationsContextProvider>
					<HeaderWrapper />
					{children}
					<Footer />
				</NotificationsContextProvider>
			</body>
		</html>
	);
}
